### PR TITLE
Fixes Blazored/Toast#195

### PR DESCRIPTION
**Pull request by Cvijo**
This should fix bug when setting Timeout on the toast instance service.

BuildToastSettings was taking Timeout from the Global instance

### CODE REVIEW

**Review by chrissainty — APPROVED** [review]
This looks great! Thanks @Cvijo

**Comment by chrissainty** [comment]
@Cvijo I've just seen your latest push. Is that for the bug fix or for the pause while hovering? If it's the latter can you revert it. This PR should only deal with the bug fix for timeout.

**Comment by Cvijo** [comment]
i don't know how to revert :) :) first time i am pulling requests :)

**Comment by Cvijo** [comment]
this should be ok now?

**Review by chrissainty — APPROVED** [review]

**Pull request merged**
