### PR TITLE
Fixed positioning bug and upgraded to preview 5

### LINKED ISSUE #13: Toast message position issue.
If my page  has a lots of information  and and I'm at  bottom of  page (after scrolling ), When clicking on show message from bottom of the page , it does show message but it show that message like I'm on top of page.

### PR DESCRIPTION
**Pull request by chrissainty**
Resolves #13 

- Updated CSS to use fixed instead of absolute for toast container

### CODE REVIEW

**Comment by iAmBipinPaul** [comment]
Hi @chrissainty 
Looks like this updates is not pushed to NuGet.

**Comment by chrissainty** [comment]
It should be there now, I got called away yesterday so didn't get a chance to publish.

**Comment by iAmBipinPaul** [comment]
Great !
IMO. It will be better to  have `nullable`  position parameter on `showError` ,`showInfo...` methods , so that we can override the default configuration whenever we need.

Also may we be we can have option show message on top center or bottom like this.
https://www.primefaces.org/primeng/#/toast
image

**Comment by chrissainty** [comment]
Sure, could you raise them as separate issues and I'll take a look as soon as I can. Also more than happy to accept a PR if you fancy having a go at one or both.

**Pull request merged**
